{{- if and .Values.database.tls.enabled (not .Values.database.tls.secretName) }}
{{- if or .Values.database.tls.cert .Values.database.tls.key .Values.database.tls.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anker-solix-exporter.fullname" . }}-db-certs
  labels:
    {{- include "anker-solix-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.database.tls.cert }}
  tls.crt: |
{{ .Values.database.tls.cert | indent 4 }}
  {{- end }}
  {{- if .Values.database.tls.key }}
  tls.key: |
{{ .Values.database.tls.key | indent 4 }}
  {{- end }}
  {{- if .Values.database.tls.caCert }}
  ca.crt: |
{{ .Values.database.tls.caCert | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
