{{- if or (not .Values.anker.existingSecret) (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anker-solix-exporter.fullname" . }}
  labels:
    {{- include "anker-solix-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.anker.existingSecret }}
  ANKER_EMAIL: {{ .Values.anker.email | quote }}
  ANKER_PASSWORD: {{ .Values.anker.password | quote }}
  {{- end }}
  {{- if and (not .Values.database.existingSecret) .Values.database.password }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}
{{- end }}
