{{- if not .Values.anker.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anker-solix-exporter.fullname" . }}
  labels:
    {{- include "anker-solix-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANKER_EMAIL: {{ .Values.anker.email | quote }}
  ANKER_PASSWORD: {{ .Values.anker.password | quote }}
  {{- if not .Values.database.existingSecret }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}
{{- end }}
